coverage:
  status:
    project:
      default: off
      "@cuaklabs/nestjs-firebase-admin":
        flags: "@cuaklabs/nestjs-firebase-admin"

flags:
  "@cuaklabs/nestjs-firebase-admin":
    paths:
      - packages/nestjs-firebase-admin/
