name: build
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/build.yml'
      - 'packages/**/*.ts'
      - 'package-lock.json'
    types:
      - closed
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
