name: Create release

on: 
  workflow_dispatch:
    
jobs:
  create-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json

      - name: Install standard-version and conventional-changelog
        run : pnpm i -g standard-version conventional-changelog-cli

      - name: Config git
        run: |
          git config --global user.email "${{ github.event.sender.email }}"
          git config --global user.name "${{ github.event.sender.login }}"

      - name: Create changelog
        run: conventional-changelog -p conventionalcommits -r 0
          
      - name: Apply standard-version
        run: |
          standard-version -t ""  --no-verify --first-release

      - name: Get new version
        id: version
        run: echo "VERSION=$(jq .version package.json -r)" >> $GITHUB_OUTPUT
      
      - name: Fix packages
        run: |
          sudo apt-get install moreutils
          jq '.version = "${{ steps.version.outputs.VERSION }}"' packages/nestjs-firebase-admin/package.json | sponge packages/nestjs-firebase-admin/package.json
          
      - name: Commit release
        run: |
          git add .
          git commit --amend --no-verify --no-edit
          git push --force
          git push --tags

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.version.outputs.VERSION }} --generate-notes
        
      
